### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by reflog** [wiggin77/audit#2]
In order to not reinvent the wheel, I think we should consider Logstash and something like: https://godoc.org/github.com/cheshir/logrus-logstash-hook

**Comment by wiggin77** [comment]
Yes, Logstash looks good for ingesting, filtering, searching, reporting.  The Logstash hook looks good for getting the logs to Logstash.

IMO Logrus incurs too much latency and creates too many allocations, but has a lot of hooks for sending data to different targets.  Zap is much better regarding latency and allocations, but is limited in that it focuses on JSON to files. 

I plan to get close to the performance of Zap while supporting all the Logrus hooks.  I have done this before [here](https://github.com/wiggin77/logr) and will steal some of my code from there to create a simplified version.  That lib benchmarked very close to Zap performance using Logrus hooks.

@reflog , let me know if that lines up with what you are thinking.  Thanks!
